allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@expo/cli"
  - "@expo/inline-modules"
  - "@expo/local-build-cache-provider"
  - "@expo/log-box"
  - "@expo/metro-config"
  - "@expo/prebuild-config"
  - "@expo/router-server"
  - babel-preset-expo
  - expo-asset
  - expo-constants
  - expo-file-system
  - expo-modules-autolinking
  - expo-modules-core
  - expo-modules-jsi
  - expo
  - "@expo/ui"
  - expo-build-properties
  - expo-haptics
  - expo-image-picker
  - expo-linking
  - expo-location
  - expo-router
  - expo-secure-store
  - expo-system-ui
  - eslint-config-expo
  - "@expo/env"
  - "@expo/fingerprint"
  - expo-font
